### ISSUE TITLE
Unown U is shiny now 

### ISSUE THREAD

**Issue by ghost** [jms412/PkmnShinyMap#1]
Hi bro,  Unown form U is  missing on file , he is shiny since event "201_21*": "",

thank for all 
regards,

**Comment by jms412** [comment]
Hey. Not really sure what to do about Unown, as they are not shiny in the wild. As far as I know they have only been shiny on incense during special events and sometimes in raids. Since the list can't currently distinguish between wild spawns and raids I have left them off the list for the time being. As soon as they are shiny in the wild I will definitely update the list.

**Comment by jms412** [comment]
Hey. I've just added a list of exceptions that I know of to the readme. As far as I'm aware, now that the ultra unlock event is over Unown U is no longer available shiny again anyway. if there's anything else that comes up more than happy for you to shout it out again :)
